icculus quake2 doxygen: C:/entry/dev/icculus-quake2/src/ref_soft/r_part.c File Reference
r_part.c File Reference
#include "r_local.h"
Classes
struct partparms_t
Macros
#define PARTICLE_33 0
#define PARTICLE_66 1
#define PARTICLE_OPAQUE 2
Functions
static byte BlendParticle33 (int pcolor, int dstcolor)
static byte BlendParticle66 (int pcolor, int dstcolor)
static byte BlendParticle100 (int pcolor, int dstcolor)
void R_DrawParticle (void)
void R_DrawParticles (void)
Variables
vec3_t r_pright
vec3_t r_pup
vec3_t r_ppn
static partparms_t partparms
Macro Definition Documentation
PARTICLE_33
#define PARTICLE_33 0
Definition at line 24 of file r_part.c.
PARTICLE_66
#define PARTICLE_66 1
Definition at line 25 of file r_part.c.
PARTICLE_OPAQUE
#define PARTICLE_OPAQUE 2
Definition at line 26 of file r_part.c.
Function Documentation
BlendParticle100()
static byte BlendParticle100 (int pcolor, int dstcolor) static
Definition at line 448 of file r_part.c.
 {
     dstcolor = dstcolor;
     return pcolor;
 }
Referenced by R_DrawParticle().
BlendParticle33()
static byte BlendParticle33 (int pcolor, int dstcolor) static
Definition at line 438 of file r_part.c.
 {
     return vid.alphamap[pcolor + dstcolor*256];
 }
Referenced by R_DrawParticle().
BlendParticle66()
static byte BlendParticle66 (int pcolor, int dstcolor) static
Definition at line 443 of file r_part.c.
 {
     return vid.alphamap[pcolor*256+dstcolor];
 }
Referenced by R_DrawParticle().
R_DrawParticle()
void R_DrawParticle (void)
Definition at line 467 of file r_part.c.
 {
     particle_t *pparticle = partparms.particle;
     int         level     = partparms.level;
     vec3_t  local, transformed;
     float   zi;
     byte    *pdest;
     short   *pz;
     int      color = pparticle->color;
     int     i, izi, pix, count, u, v;
     byte  (*blendparticle)( int, int );
     /*
     ** transform the particle
     */
     VectorSubtract (pparticle->origin, r_origin, local);
     transformed[0] = DotProduct(local, r_pright);
     transformed[1] = DotProduct(local, r_pup);
     transformed[2] = DotProduct(local, r_ppn);
     if (transformed[2] < PARTICLE_Z_CLIP)
         return;
     /*
     ** bind the blend function pointer to the appropriate blender
     */
     if ( level == PARTICLE_33 )
         blendparticle = BlendParticle33;
     else if ( level == PARTICLE_66 )
         blendparticle = BlendParticle66;
     else
         blendparticle = BlendParticle100;
     /*
     ** project the point
     */
     // FIXME: preadjust xcenter and ycenter
     zi = 1.0 / transformed[2];
     u = (int)(xcenter + zi * transformed[0] + 0.5);
     v = (int)(ycenter - zi * transformed[1] + 0.5);
     if ((v > d_vrectbottom_particle) ||
         (u > d_vrectright_particle) ||
         (v < d_vrecty) ||
         (u < d_vrectx))
     {
         return;
     }
     /*
     ** compute addresses of zbuffer, framebuffer, and
     ** compute the Z-buffer reference value.
     */
     pz = d_pzbuffer + (d_zwidth * v) + u;
     pdest = d_viewbuffer + d_scantable[v] + u;
     izi = (int)(zi * 0x8000);
     /*
     ** determine the screen area covered by the particle,
     ** which also means clamping to a min and max
     */
     pix = izi >> d_pix_shift;
     if (pix < d_pix_min)
         pix = d_pix_min;
     else if (pix > d_pix_max)
         pix = d_pix_max;
     /*
     ** render the appropriate pixels
     */
     count = pix;
     switch (level) {
     case PARTICLE_33 :
         for ( ; count ; count--, pz += d_zwidth, pdest += r_screenwidth)
         {
 //FIXME--do it in blocks of 8?
             for (i=0 ; i<pix ; i++)
             {
                 if (pz[i] <= izi)
                 {
                     pz[i]    = izi;
                     pdest[i] = vid.alphamap[color + ((int)pdest[i]<<8)];
                 }
             }
         }
         break;
     case PARTICLE_66 :
         for ( ; count ; count--, pz += d_zwidth, pdest += r_screenwidth)
         {
             for (i=0 ; i<pix ; i++)
             {
                 if (pz[i] <= izi)
                 {
                     pz[i]    = izi;
                     pdest[i] = vid.alphamap[(color<<8) + (int)pdest[i]];
                 }
             }
         }
         break;
     default:  //100
         for ( ; count ; count--, pz += d_zwidth, pdest += r_screenwidth)
         {
             for (i=0 ; i<pix ; i++)
             {
                 if (pz[i] <= izi)
                 {
                     pz[i]    = izi;
                     pdest[i] = color;
                 }
             }
         }
         break;
     }
 }
Referenced by R_DrawParticles().
R_DrawParticles()
void R_DrawParticles (void)
Definition at line 596 of file r_part.c.
 {
     particle_t *p;
     int         i;
 #if id386 && !defined __linux__ && !defined __FreeBSD__
     extern unsigned long fpu_sp24_cw, fpu_chop_cw;
 #endif
     VectorScale( vright, xscaleshrink, r_pright );
     VectorScale( vup, yscaleshrink, r_pup );
     VectorCopy( vpn, r_ppn );
 #if id386 && !defined __linux__ && !defined __FreeBSD__
     __asm fldcw word ptr [fpu_sp24_cw]
 #endif
     for (p=r_newrefdef.particles, i=0 ; i<r_newrefdef.num_particles ; i++,p++)
     {
         if ( p->alpha > 0.66 )
             partparms.level = PARTICLE_OPAQUE;
         else if ( p->alpha > 0.33 )
             partparms.level = PARTICLE_66;
         else
             partparms.level = PARTICLE_33;
         partparms.particle = p;
         partparms.color    = p->color;
 #if id386 && !defined __linux__ && !defined __FreeBSD__
         if ( i < r_newrefdef.num_particles-1 )
             s_prefetch_address = ( unsigned int ) ( p + 1 );
         else
             s_prefetch_address = ( unsigned int ) r_newrefdef.particles;
 #endif
         R_DrawParticle();
     }
 #if id386 && !defined __linux__ && !defined __FreeBSD__
     __asm fldcw word ptr [fpu_chop_cw]
 #endif
 }
Variable Documentation
partparms
partparms_t partparms static
Definition at line 35 of file r_part.c.
Referenced by R_DrawParticle(), and R_DrawParticles().
r_ppn
vec3_t r_ppn
Definition at line 22 of file r_part.c.
Referenced by R_DrawParticle(), and R_DrawParticles().
r_pright
vec3_t r_pright
Definition at line 22 of file r_part.c.
Referenced by R_DrawParticle(), and R_DrawParticles().
r_pup
vec3_t r_pup
Definition at line 22 of file r_part.c.
Referenced by R_DrawParticle(), and R_DrawParticles().